import pandas as pd
import numpy as np

def compute_features(df: pd.DataFrame, is_training: bool = True) -> pd.DataFrame:
    """
    Computes time-based, lag, rolling, and target features.
    
    Args:
        df: DataFrame containing raw weather and aqi hourly data, ordered by time.
        is_training: If True, computes forward-looking targets (t+24, t+48, t+72).
    """
    df = df.copy()
    
    # 1. Time-based features
    df["hour"] = df["time"].dt.hour
    df["day_of_week"] = df["time"].dt.dayofweek
    df["month"] = df["time"].dt.month
    df["is_weekend"] = df["day_of_week"].isin([5, 6]).astype(int)
    
    # Season (approximate for Pakistan: 12-2 Winter, 3-5 Spring, 6-9 Summer/Monsoon, 10-11 Autumn)
    # Mapping month to season: 1: Winter, 2: Spring, 3: Summer, 4: Autumn
    month_to_season = {
        12: 1, 1: 1, 2: 1,
        3: 2, 4: 2, 5: 2,
        6: 3, 7: 3, 8: 3, 9: 3,
        10: 4, 11: 4
    }
    df["season"] = df["month"].map(month_to_season)
    
    # Cast all integer features to int64 to prevent Hopsworks schema mismatches (bigint vs int)
    int_cols = ["hour", "day_of_week", "month", "is_weekend", "season"]
    for col in int_cols:
        df[col] = df[col].astype("int64")
    
    # Sort by time to ensure windowing works correctly
    df = df.sort_values("time").reset_index(drop=True)
    
    # We apply shifts and rolling per city, but since we process per city anyway before concatenating,
    # we don't necessarily need a groupby here if we guarantee one city per call.
    # However, for safety, let's group by city.
    
    grouped = df.groupby("city")
    
    # 2. Lag features
    lags = [1, 3, 6, 24, 48]
    for lag in lags:
        df[f"us_aqi_lag_{lag}"] = grouped["us_aqi"].shift(lag)
        df[f"pm2_5_lag_{lag}"] = grouped["pm2_5"].shift(lag)
        
    # AQI rate of change (difference between current and 1h ago)
    df["us_aqi_diff_1"] = df["us_aqi"] - df["us_aqi_lag_1"]
    
    # 3. Rolling window features
    windows = [6, 24, 168]  # 6h, 24h, 7-day
    for w in windows:
        # Min
        df[f"us_aqi_roll_min_{w}"] = grouped["us_aqi"].rolling(window=w, min_periods=1).min().reset_index(level=0, drop=True)
        # Max
        df[f"us_aqi_roll_max_{w}"] = grouped["us_aqi"].rolling(window=w, min_periods=1).max().reset_index(level=0, drop=True)
        # Mean
        df[f"us_aqi_roll_mean_{w}"] = grouped["us_aqi"].rolling(window=w, min_periods=1).mean().reset_index(level=0, drop=True)
        # Std (will be NaN for 1 element window, we fill later)
        df[f"us_aqi_roll_std_{w}"] = grouped["us_aqi"].rolling(window=w, min_periods=1).std().reset_index(level=0, drop=True)
        
        df[f"pm2_5_roll_mean_{w}"] = grouped["pm2_5"].rolling(window=w, min_periods=1).mean().reset_index(level=0, drop=True)

    # 4. Target features (Only if training / backfilling)
    if is_training:
        df["target_us_aqi_24h"] = grouped["us_aqi"].shift(-24)
        df["target_us_aqi_48h"] = grouped["us_aqi"].shift(-48)
        df["target_us_aqi_72h"] = grouped["us_aqi"].shift(-72)
        
        # We drop rows where target is NaN (i.e. the very end of our dataset)
        df = df.dropna(subset=["target_us_aqi_72h"])

    # Fill NaNs generated by shifting/rolling with forward fill, then backward fill or 0
    df = df.ffill().fillna(0)
    
    return df
