name: AQI Feature Pipeline

on:
  workflow_dispatch:
    inputs:
      run_backfill:
        description: 'Run historical backfill instead of hourly update'
        required: true
        default: 'false'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
          PYTHONPATH: .
        run: |
          if [ "${{ github.event.inputs.run_backfill }}" == "true" ]; then
            python feature_pipeline/backfill.py
          else
            python feature_pipeline/pipeline.py
          fi
